"""empty message

Revision ID: 721cd7399126
Revises: db91d6e7bdb8
Create Date: 2017-04-05 18:08:51.008705

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger

# revision identifiers, used by Alembic.
revision = '721cd7399126'
down_revision = 'db91d6e7bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('law', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_law_search_vector', 'law', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('page', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_page_search_vector', 'page', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('post', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_post_search_vector', 'post', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('proposal', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_proposal_search_vector', 'proposal', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('topic', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_topic_search_vector', 'topic', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('user', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_user_search_vector', 'user', ['search_vector'], unique=False, postgresql_using='gin')
    # ### manually inserted searchable sync ###
    conn = op.get_bind()
    sync_trigger(conn, 'law', 'search_vector', ['content'])
    sync_trigger(conn, 'page', 'search_vector', ['title', 'content'])
    sync_trigger(conn, 'post', 'search_vector', ['content'])
    sync_trigger(conn, 'proposal', 'search_vector', ['description'])
    sync_trigger(conn, 'topic', 'search_vector', ['name', 'description'])
    sync_trigger(conn, 'user', 'search_vector', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_search_vector', table_name='user')
    op.drop_column('user', 'search_vector')
    op.drop_index('ix_topic_search_vector', table_name='topic')
    op.drop_column('topic', 'search_vector')
    op.drop_index('ix_proposal_search_vector', table_name='proposal')
    op.drop_column('proposal', 'search_vector')
    op.drop_index('ix_post_search_vector', table_name='post')
    op.drop_column('post', 'search_vector')
    op.drop_index('ix_page_search_vector', table_name='page')
    op.drop_column('page', 'search_vector')
    op.drop_index('ix_law_search_vector', table_name='law')
    op.drop_column('law', 'search_vector')
    # ### end Alembic commands ###
