"""empty message

Revision ID: 7e7eb4243802
Revises: 3ba2f7f3ff33
Create Date: 2017-01-12 11:48:41.992347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7eb4243802'
down_revision = '3ba2f7f3ff33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_mailing_list')
    op.drop_table('email')
    op.add_column('mailing_list', sa.Column('url', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'mailing_list', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mailing_list', type_='unique')
    op.drop_column('mailing_list', 'url')
    op.create_table('email',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('email_id_seq'::regclass)"), nullable=False),
    sa.Column('value', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'email_pkey'),
    sa.UniqueConstraint('value', name=u'email_value_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('email_mailing_list',
    sa.Column('mailing_list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_id'], [u'email.id'], name=u'email_mailing_list_email_id_fkey'),
    sa.ForeignKeyConstraint(['mailing_list_id'], [u'mailing_list.id'], name=u'email_mailing_list_mailing_list_id_fkey')
    )
    # ### end Alembic commands ###
