"""empty message

Revision ID: a941ad1345a2
Revises: 23a96bfba90a
Create Date: 2017-02-05 17:59:28.943259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a941ad1345a2'
down_revision = '23a96bfba90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('vote_day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'vote_day')
    # ### end Alembic commands ###
