"""empty message

Revision ID: b224c3fed517
Revises: eb58dc30411e
Create Date: 2017-01-17 19:44:52.956142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b224c3fed517'
down_revision = 'eb58dc30411e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'law_group', ['name'])
    op.create_unique_constraint(None, 'law_status', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'law_status', type_='unique')
    op.drop_constraint(None, 'law_group', type_='unique')
    # ### end Alembic commands ###
