"""empty message

Revision ID: eb58dc30411e
Revises: 1e6e58e9af1d
Create Date: 2017-01-14 17:33:42.943623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb58dc30411e'
down_revision = '1e6e58e9af1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('law_add',
    sa.Column('law_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], )
    )
    op.create_table('law_law_group',
    sa.Column('law_id', sa.Integer(), nullable=True),
    sa.Column('law_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['law_group_id'], ['law_group.id'], ),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], )
    )
    op.create_table('law_remove',
    sa.Column('law_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], )
    )
    op.drop_table('law_proposal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_proposal',
    sa.Column('law_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['law_id'], [u'law.id'], name=u'law_proposal_law_id_fkey'),
    sa.ForeignKeyConstraint(['proposal_id'], [u'proposal.id'], name=u'law_proposal_proposal_id_fkey')
    )
    op.drop_table('law_remove')
    op.drop_table('law_law_group')
    op.drop_table('law_add')
    op.drop_table('law_group')
    # ### end Alembic commands ###
